databases:
  - name: lightsaberbay
    databaseName: lightsaberbay
    user: lightsaberbay

services:
  - type: web
    name: lightsaberbay
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lightsaberbay
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
